name: Ship js trigger
on:
  pull_request:
    types:
      - closed
jobs:
  publish-to-npm:
    name: 'Publishing to NPM ✨'
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/v')
    steps:
      - name: Checkout code 🛎
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup GitHub Actor
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Setup node environment 📦
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: 'npm'

      - name: Install dependencies 🚀
        run: npm ci --prefer-offline --no-audit

      - name: Trigger a release (NPM) 🥳
        run: npx shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}

  publish-to-jsr:
    name: 'Publishing to JSR ✨'
    runs-on: ubuntu-latest
    needs: publish-to-npm
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code 🛎
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Trigger a release (JSR) 🥳
        run: npx jsr publish
