name: Ship js trigger

on:
  pull_request:
    types:
      - closed

jobs:
  publish-to-npm:
    name: 'Publishing to NPM ✨'
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/v')
    steps:
      - name: Checkout code 🛎
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup GitHub Actor
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Setup bun env 🐰
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies 🚀
        run: bun install --frozen-lockfile

      - name: Trigger a release (NPM) 🥳
        run: bunx shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}

  publish-to-jsr:
    name: 'Publishing to JSR ✨'
    runs-on: ubuntu-latest
    needs: publish-to-npm
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code 🛎
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Trigger a release (JSR) 🥳
        run: npx jsr publish
